name: Build Docker container
on:
  push:
    branches:
      - main
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      buildDockerImage:
        description: 'Build Docker image'
        required: true
        type: boolean
defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-container:
    name: Build Docker container
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    # Set up Buildx. We use this so we can explicitly set cache export flags.
    # This allows us to cache _all_ intermediates layers to be cached (using
    # BuildKit's mode=max flag) rather than just layers of the resulting image
    # (which is the default). This dramatically improves our build times because
    # we use an intermediate container to run the cabal build (including all of
    # our dependencies!), and mode=max is required to cache that intermediate
    # container and its really expensive dependency layer.
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Package Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Calculate Docker tag names
      uses: docker/metadata-action@v4
      id: docker-meta
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=long
          type=semver,pattern=v{{version}}

    - name: Build and push container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
